#! /bin/bash

if [ $# -ne 2 ];
then
	echo "runDROP [FASTA file] [Output dir]"
	exit 1
fi

#cd ${DROP_DIR}

base=`basename "${1}" .fasta`

test -d ${2}/VectorElements/ || mkdir ${2}/VectorElements/
test -d ${2}/PSSM/ || mkdir ${2}/PSSM/

# Make param -- AAIndex, Shannon's entropy and linker likelihood score (domain)
./bin/Convert2Param ${1} ./ref/AAINDEX/BLAM930101.txt 11 > ${2}/VectorElements/BLAM930101_11.txt
./bin/Convert2Param ${1} ./ref/AAINDEX/CHOP780213.txt 11 > ${2}/VectorElements/CHOP780213_11.txt
./bin/Convert2Param ${1} ./ref/AAINDEX/TANS770104.txt 11 > ${2}/VectorElements/TANS770104_11.txt
./bin/Convert2Param ${1} ./ref/AAINDEX/LINKERLIKELIHOOD_DOMAIN.txt 11 > ${2}/VectorElements/LINKERLIKELIHOOD_DOMAIN_11.txt
./bin/CalcShannons_Entropy ${1} 41 > ${2}/VectorElements/ShannonE_41.txt

#Run PSI-BLAST
./Script/MakePSSM.sh ./ref/option.txt ${1} ${2}/PSSM/
./bin/MTX2PSSM ${2}/PSSM/${base}.mtx ${2}/PSSM/${base}.pssm

# Make param -- PSSM
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm P  1 > ${2}/VectorElements/PSSM_P_1.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm P 11 > ${2}/VectorElements/PSSM_P_11.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm P 21 > ${2}/VectorElements/PSSM_P_21.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm P 31 > ${2}/VectorElements/PSSM_P_31.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm P 41 > ${2}/VectorElements/PSSM_P_41.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm K 11 > ${2}/VectorElements/PSSM_K_11.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm K 21 > ${2}/VectorElements/PSSM_K_21.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm K 31 > ${2}/VectorElements/PSSM_K_31.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm K 41 > ${2}/VectorElements/PSSM_K_41.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm T 11 > ${2}/VectorElements/PSSM_T_11.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm T 21 > ${2}/VectorElements/PSSM_T_21.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm T 31 > ${2}/VectorElements/PSSM_T_31.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm R 11 > ${2}/VectorElements/PSSM_R_11.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm R 21 > ${2}/VectorElements/PSSM_R_21.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm R 41 > ${2}/VectorElements/PSSM_R_41.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm E 21 > ${2}/VectorElements/PSSM_E_21.txt
./bin/ConvertPSSM2Param ${2}/PSSM/${base}.pssm S 21 > ${2}/VectorElements/PSSM_S_21.txt

# Run PSI-PRED
./Script/MakePSS.sh ./ref/option.txt ${2} ${base}
#Make param -- PSS
./bin/ConvertPSIPRED2Param ${2}/PSIPRED/${base}.ss2 ${2}/VectorElements/ 1

#Prediction
./bin/MakeVector ./ref/DROP-SD3.txt ${2}/VectorElements/ > ${2}/${base}.vec
./Script/RunSVMLight.sh ./ref/option.txt ./ref/Model/model.txt ${2} ${base}
./bin/Smoothing ${2}/SVM_Output/${base}.txt 5 ${2}/SVM_Output/smoothed.txt QUERY${base}

#Make option file for getting predicted linkers
cat ./ref/option_DROP_TMP.txt > ${2}/option_DROP.txt
echo "NormalizedFile = ${2}/SVM_Output/smoothed.txt" >> ${2}/option_DROP.txt
echo "OutputFile = ${2}/${base}_pred.txt" >> ${2}/option_DROP.txt

./bin/GetPredictedLinker ${2}/option_DROP.txt 1 -0.2

